obj-y += 	main.o \
		eabi_compat.o \
		delay.o \
		calibrate.o \
		thread.o \
		schedule.o \
		mutex.o  \
		spinlock.o \
		sync.o \
		syscalls.o

obj-$(CONFIG_MMU) += process.o

obj-y += softirq.o
obj-y += fdt.o
